package it.itwtech.ateauth.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import it.itwtech.ateauth.dto.DeliveryBoyBranchUpdateDto;
import it.itwtech.ateauth.model.BranchAdmin;
import it.itwtech.ateauth.model.DeliveryBoy;
import it.itwtech.ateauth.model.User;


@Service
public class MailNotificationsServicesImpl implements MailNotificationsServices {
  @Autowired
  private EmailClintService emailClintService;
  @Value("${forentend.url}")
  private String forentEndUrl;
  @Value("${forentend.url.verification}")
  private String forentEndUrlVerify;


  @Async
  @Transactional
  public void forgotMail(String mail, String token, String origin) {
    emailClintService.sendHtmlMail(mail, "Forgot Password",
        "<body marginheight=\"0\" topmargin=\"0\" marginwidth=\"0\" style=\"margin: 0px; background-color: #f2f3f8;\" leftmargin=\"0\">\r\n"
            + "    <!--100% body table-->\r\n"
            + "    <table cellspacing=\"0\" border=\"0\" cellpadding=\"0\" width=\"100%\" bgcolor=\"#f2f3f8\"\r\n"
            + "        style=\"@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700); font-family: 'Open Sans', sans-serif;\">\r\n"
            + "        <tr>\r\n" + "            <td>\r\n"
            + "                <table style=\"background-color: #f2f3f8; max-width:670px;  margin:0 auto;\" width=\"100%\" border=\"0\"\r\n"
            + "                    align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
            + "                    <tr>\r\n"
            + "                        <td style=\"height:80px;\">&nbsp;</td>\r\n"
            + "                    </tr>\r\n" + "                    <tr>\r\n"
            + "                        <td style=\"text-align:center;\">\r\n"
            + "                          <a href=\"https://rakeshmandal.com\" title=\"logo\" target=\"_blank\">\r\n"
            + "                            <img width=\"60\" src=\"https://i.ibb.co/hL4XZp2/android-chrome-192x192.png\" title=\"logo\" alt=\"logo\">\r\n"
            + "                          </a>\r\n" + "                        </td>\r\n"
            + "                    </tr>\r\n" + "                    <tr>\r\n"
            + "                        <td style=\"height:20px;\">&nbsp;</td>\r\n"
            + "                    </tr>\r\n" + "                    <tr>\r\n"
            + "                        <td>\r\n"
            + "                            <table width=\"95%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"\r\n"
            + "                                style=\"max-width:670px;background:#fff; border-radius:3px; text-align:center;-webkit-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);-moz-box-shadow:0 6px 18px 0 rgba(0,0,0,.06);box-shadow:0 6px 18px 0 rgba(0,0,0,.06);\">\r\n"
            + "                                <tr>\r\n"
            + "                                    <td style=\"height:40px;\">&nbsp;</td>\r\n"
            + "                                </tr>\r\n"
            + "                                <tr>\r\n"
            + "                                    <td style=\"padding:0 35px;\">\r\n"
            + "                                        <h1 style=\"color:#1e1e2d; font-weight:500; margin:0;font-size:32px;font-family:'Rubik',sans-serif;\">You have\r\n"
            + "                                            requested to reset your password</h1>\r\n"
            + "                                        <span\r\n"
            + "                                            style=\"display:inline-block; vertical-align:middle; margin:29px 0 26px; border-bottom:1px solid #cecece; width:100px;\"></span>\r\n"
            + "                                        <p style=\"color:#455056; font-size:15px;line-height:24px; margin:0;\">\r\n"
            + "                                            We cannot simply send you your old password. A unique link to reset your\r\n"
            + "                                            password has been generated for you. To reset your password, click the\r\n"
            + "                                            following link and follow the instructions.\r\n"
            + "                                        </p>\r\n"
            + "                                        <p style=\"-ms-text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: 100%; color: #104be6; font-family: 'Postmates Std', 'Helvetica', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif; font-size: 16px; font-smoothing: always; font-style: normal; font-weight: 400; letter-spacing: -0.18px; line-height: 24px; mso-line-height-rule: exactly; text-decoration: none; vertical-align: top; width: 100%;\">\r\n"
            + "                                         Token : " + token + "\r\n"
            + "                                        </p>\r\n" + " <a href='" + origin
            + forentEndUrl + "' "
            + " style=\"background:#20e277;text-decoration:none !important; font-weight:500; margin-top:35px; color:#fff;text-transform:uppercase; font-size:14px;padding:10px 24px;display:inline-block;border-radius:50px;\">Reset Password</a>\r\n"
            + "                                    </td>\r\n"
            + "                                </tr>\r\n"
            + "                                <tr>\r\n"
            + "                                    <td style=\"height:40px;\">&nbsp;</td>\r\n"
            + "                                </tr>\r\n"
            + "                            </table>\r\n" + "                        </td>\r\n"
            + "                    <tr>\r\n"
            + "                        <td style=\"height:20px;\">&nbsp;</td>\r\n"
            + "                    </tr>\r\n" + "                    <tr>\r\n"
            + "                        <td style=\"height:80px;\">&nbsp;</td>\r\n"
            + "                    </tr>\r\n" + "                </table>\r\n"
            + "            </td>\r\n" + "        </tr>\r\n" + "    </table>\r\n"
            + "    <!--/100% body table-->\r\n" + "</body>"

    );
  }

  @Async
  @Transactional
  public void passwordResetSuccess(String mail) {
    emailClintService.sendHtmlMail(mail, "Forgot Password",
        "\r\n" + "<body>" + "<h2>Password reset succesfully</h2>" + "</body>");
  }

  @Async
  @Transactional
  public void sendTemporaryUserPasswordEmail(String email, User user, String password) {
    emailClintService.sendHtmlMail(email, "Successfully Registered",
        "<body style=\"background-color: #fff; margin: 0; padding: 0\">\r\n" + "    <table\r\n"
            + "        class=\"main\"\r\n" + "        align=\"center\"\r\n"
            + "        width=\"600px\"\r\n" + "        style=\"background-color: #ffffff\"\r\n"
            + "    >\r\n" + "        <tbody>\r\n" + "            <tr>\r\n"
            + "                <td>\r\n" + "                    <table\r\n"
            + "                        class=\"title\"\r\n"
            + "                        border=\"0\"\r\n"
            + "                        cellpadding=\"0\"\r\n"
            + "                        cellspacing=\"0\"\r\n"
            + "                        role=\"presentation\"\r\n" + "                    >\r\n"
            + "                        <tr>\r\n"
            + "                            <td width=\"75px\">\r\n"
            + "                                <img\r\n"
            + "                                    style=\"width: 56px; padding: 5px\"\r\n"
            + "                                    src=\"https://www.udrop.com/cache/plugins/filepreviewer/681390/9baceaa7eb7ddf952f5a8c76ba6cae947421b9cbabb4b14d3a9fd4201e4b2dd4/280x280_middle.jpg\"\r\n"
            + "                                />\r\n" + "                            </td>\r\n"
            + "                            <td>\r\n" + "                                <div>\r\n"
            + "                                    <span\r\n"
            + "                                        style=\"\r\n"
            + "                                            font-weight: 400;\r\n"
            + "                                            font-size: 24px;\r\n"
            + "                                            font-family: Roboto, Tahoma, Verdana,\r\n"
            + "                                                Segoe, sans-serif;\r\n"
            + "                                            color: #000000;\r\n"
            + "                                        \"\r\n"
            + "                                        ><strong>Fleet Management</strong></span\r\n"
            + "                                    >\r\n"
            + "                                </div>\r\n" + "                            </td>\r\n"
            + "                        </tr>\r\n" + "                    </table>\r\n"
            + "                    <table\r\n"
            + "                        class=\"illustration\"\r\n"
            + "                        align=\"center\"\r\n"
            + "                        border=\"0\"\r\n"
            + "                        cellpadding=\"0\"\r\n"
            + "                        cellspacing=\"0\"\r\n"
            + "                        role=\"presentation\"\r\n" + "                    >\r\n"
            + "                        <tr>\r\n" + "                            <td>\r\n"
            + "                                <img\r\n"
            + "                                    style=\"\r\n"
            + "                                        width: 320px;\r\n"
            + "                                        height: 240px;\r\n"
            + "                                        object-fit: cover;\r\n"
            + "                                    \"\r\n"
            + "                                    src=\"https://www.udrop.com/cache/plugins/filepreviewer/681391/c218c890aacdfe9ac01aad33eb8dd5ad520f37ce125aa4091ae5f64d6d4b3d39/280x280_middle.jpg\"\r\n"
            + "                                />\r\n" + "                            </td>\r\n"
            + "                        </tr>\r\n" + "                    </table>\r\n"
            + "                    <table\r\n" + "                        class=\"content\"\r\n"
            + "                        width=\"500px\"\r\n"
            + "                        align=\"center\"\r\n"
            + "                        border=\"0\"\r\n"
            + "                        cellpadding=\"0\"\r\n"
            + "                        cellspacing=\"0\"\r\n"
            + "                        role=\"presentation\"\r\n" + "                    >\r\n"
            + "                        <tr>\r\n" + "                            <td>\r\n"
            + "                                <span\r\n"
            + "                                    style=\"\r\n"
            + "                                        font-weight: 400;\r\n"
            + "                                        font-size: 35px;\r\n"
            + "                                        font-family: Roboto, Tahoma, Verdana,\r\n"
            + "                                            Segoe, sans-serif;\r\n"
            + "                                        color: #141b55;\r\n"
            + "                                    \"\r\n"
            + "                                    ><strong>Welcome !</strong></span\r\n"
            + "                                >\r\n" + "                            </td>\r\n"
            + "                        </tr>\r\n" + "                        <tr>\r\n"
            + "                            <td>\r\n" + "                                <p>\r\n"
            + "                                    <span\r\n"
            + "                                        style=\"\r\n"
            + "                                            font-size: 20px;\r\n"
            + "                                            font-family: Roboto, Tahoma, Verdana,\r\n"
            + "                                                Segoe, sans-serif;\r\n"
            + "                                        \"\r\n"
            + "                                        >You have successfully registered Fleet\r\n"
            + "                                        Management Corporate account.</span\r\n"
            + "                                    >\r\n"
            + "                                </p>\r\n" + "                            </td>\r\n"
            + "                        </tr>\r\n" + "                    </table>\r\n" + "\r\n"
            + "                    <table\r\n" + "                        class=\"content\"\r\n"
            + "                        width=\"500px\"\r\n"
            + "                        align=\"center\"\r\n"
            + "                        border=\"0\"\r\n"
            + "                        cellpadding=\"0\"\r\n"
            + "                        cellspacing=\"0\"\r\n"
            + "                        role=\"presentation\"\r\n" + "                    >\r\n"
            + "                        <tr>\r\n" + "                            <td>\r\n"
            + "                                <span\r\n"
            + "                                    style=\"\r\n"
            + "                                        font-weight: 400;\r\n"
            + "                                        font-size: 18px;\r\n"
            + "                                        font-family: Roboto, Tahoma, Verdana,\r\n"
            + "                                            Segoe, sans-serif;\r\n"
            + "                                        color: #000000;\r\n"
            + "                                        padding-left: 150px;\r\n"
            + "                                    \"\r\n"
            + "                                    ><strong>User Name:</strong>\r\n"
            + "                                    <span style=\"width: 10px\"></span>\r\n"
            + "                                    <span style=\"color: #141b55\"\r\n"
            + "                                        >" + user.getEmail() + "</span\r\n"
            + "                                    ></span\r\n"
            + "                                >\r\n" + "                            </td>\r\n"
            + "                        </tr>\r\n" + "                        <tr>\r\n"
            + "                            <td>\r\n" + "                                <span\r\n"
            + "                                    style=\"\r\n"
            + "                                        font-weight: 400;\r\n"
            + "                                        font-size: 18px;\r\n"
            + "                                        font-family: Roboto, Tahoma, Verdana,\r\n"
            + "                                            Segoe, sans-serif;\r\n"
            + "                                        color: #030303;\r\n"
            + "                                        padding-left: 150px;\r\n"
            + "                                    \"\r\n"
            + "                                    ><strong>Password:</strong>\r\n"
            + "                                    <span style=\"width: 80px\"></span\r\n"
            + "                                    ><span style=\"color: #141b55\"\r\n"
            + "                                        >" + password + "</span\r\n"
            + "                                    ></span\r\n"
            + "                                >\r\n" + "                            </td>\r\n"
            + "                        </tr>\r\n" + "                    </table>\r\n" + "\r\n"
            + "                    <table\r\n" + "                        class=\"footer\"\r\n"
            + "                        border=\"0\"\r\n"
            + "                        cellpadding=\"0\"\r\n"
            + "                        cellspacing=\"0\"\r\n"
            + "                        role=\"presentation\"\r\n" + "                    >\r\n"
            + "                        <tr height=\"40px\"></tr>\r\n"
            + "                        <tr>\r\n" + "                            <td\r\n"
            + "                                height=\"80px\"\r\n"
            + "                                width=\"600px\"\r\n"
            + "                                bgcolor=\"#030621\"\r\n"
            + "                                align=\"center\"\r\n"
            + "                            >\r\n" + "                                <p\r\n"
            + "                                    style=\"\r\n"
            + "                                        font-size: 14px;\r\n"
            + "                                        font-family: Roboto, Tahoma, Verdana,\r\n"
            + "                                            Segoe, sans-serif;\r\n"
            + "                                        color: #ffffff;\r\n"
            + "                                    \"\r\n" + "                                >\r\n"
            + "                                    � 2022 Invicta Innovations. All rights\r\n"
            + "                                    reserved.\r\n"
            + "                                </p>\r\n" + "                            </td>\r\n"
            + "                        </tr>\r\n" + "                    </table>\r\n"
            + "                </td>\r\n" + "            </tr>\r\n" + "        </tbody>\r\n"
            + "    </table>\r\n" + "</body>\r\n" + "");

  }

  @Async
  @Transactional
  public void sendVerifyEmail(String email, String token) {
    emailClintService.sendHtmlMail(email, "Email Verification",
        "<body style=\"background-color:#fff; margin:0;padding:0;\"><script type=\"text/javascript\" src=\"https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=uWQYkQcUkiR3yTzQOvhyHhfMCdJqQmBI4bf9gj6pwuCpOyq9WurNHCBeyn0DShbiTt6k_61S9hUXXwmct_ZXvQYVh_ekEZ_3WO0ySS1Bhrr8E3U-g2enfvI3vermQ_mxhr16DtKdX1zQD_mohdxzwe_BNcObs3xAUM9eyES6grwRql3ZdOaDZB1RbzQxU7eszw1oHiqZ0XQLjFsXubYdm3plic1wyOPck9k73lZXXtn_5mfv60T5cQHHpQz7GtDCt_NHeEAMWJlnGuvBW4DzipVJ8GFQV2Az8wNWPvTRviPatf-HPO4wnGWPxilcQriHzRuYzuyxs4kI2gJP-oeUdnfLjEhi59sUxI01yLPXbhQvWKPSqktKdETkhad_cEtq0XZBRu3W6fn7sbqCOwS7vJpNcNThGB5TYgRUxm9rPV5fu8PbNrEqzrbe39iNrqVk3N6oVzKz0oN35mVdoPjp89iEKoLtuHv4VtIE3D0q8NMDsyZBbRKD8gCv9sIjCZJvd0eK1KLToe3PBml8YTQGK6yacmP_BVHNmlIcOwS-VTaSwluyLP1Zi_O36SUQrsSQ5vKcNaLkjJ2sN-p4TbPSmd45uwEThn9JrMr3_FCCm5RC7YKb9yOWdKDUgvz5iipzO_lTxU5njmdmiAgCwhh5NkOGAs2o6rBI_KG9Lo34mi0NfleJND1OhGuw75ap92RX9BkDm53VQ1sZv-21wAkHwyFgMxodvPUQ2GTqkvviWlp7L-iIpC8AQIGxbGFP5a7EExsSaQUdcGgkDH8VPv7mRT8pkamBV-jn3REy0G8YFpryC5AdnwGBlMjlPjqZrAQHwFhWf-HSZL1XeLPa-0fuaIohM6vldYZbC22bbnO2WAiN9K5TBtvA4cjgctFvHdWD2k_dLLFg-uPiMTH0y99Lrs8m5vQteU3CXGyIHfDjPZWU2eoqCNr_Q6GxdNR_iHdJAK9bKmPdp8921Y0JTxXJJ0uI-cfCR9w7uZYgJGX-tVd0q-GZX93C4D-CRzAVm_tck9ZPuwB94wzZfwrSM0UgeZFtxc5AmhkiS9FnS7H8jeFHpOdmwaTehGLXE0lYAs7oS5AC6CRjJaji0sowlF9_cauPrTYaw5oSjqBGYN95WCZSQ1BBCrL3wT0E0GkRkPiYHTEpD7hNVlkt-l-9b4aJe25KMF3pE4WCFrLTEiR0Yon_5oKCX2ApAH7iEKWZT30u__qAvfy79z0IfDbfZe2uGQp-a_HwGUOG6Mt7ZRFlD-1mu0Bp4YSBKg-TVdo-dPSwy8Z4S5cvI4d9ghh_DoNnQpB1esqMw0P8U1flsTrE5AvLUjG2Heok8ApImTSPnyaR\" nonce=\"2d9d35df038e8914d8b3ca29bf3da3e2\" charset=\"UTF-8\"></script>\r\n"
            + "  <table class=\"main\" align=\"center\" width=\"600px\" style=\"background-color: #ffffff;\">\r\n"
            + "  <tbody>\r\n" + "    <tr>\r\n" + "    <td>\r\n"
            + "    <table class=\"title\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "     <tr>\r\n" + "       <td width=\"75px\">\r\n"
            + "         <img style=\"width: 56px; padding: 5px;\"src=\"https://www.udrop.com/cache/plugins/filepreviewer/681390/9baceaa7eb7ddf952f5a8c76ba6cae947421b9cbabb4b14d3a9fd4201e4b2dd4/280x280_middle.jpg\"/>\r\n"
            + "       </td>\r\n" + "       <td>\r\n"
            + "         <div> <span style=\"font-weight:400;font-size:24px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#000000;\"><strong>Fleet Management</strong></span> </div>\r\n"
            + "       </td>\r\n" + "     </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"illustration\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td>\r\n"
            + "        <img style=\"width: 260px; height: 220px; object-fit: cover\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681394/08cce7223850b4e99abcee6b4968625871aa764e592f74ffdd7ddfe9a0f3bf2f/280x280_middle.jpg\"/>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"content\" width=\"500px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td align=\"center\">\r\n"
            + "        <p><span style=\"font-size:18px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;font-weight: bold;\">Authorize your SignUp using the One Time Password below:</span></p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "    <tr height=\"80px\">\r\n"
            + "      <td align=\"center\">\r\n"
            + "        <span style=\"font-weight:400;font-size:35px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#008175;\"><strong>"
            + token + "</strong></span>\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
            + "      <td align=\"center\">\r\n"
            + "        <p><span style=\"font-size:15px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif\">This activation code expires in 10 minutes</span></p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"footer\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr height=\"30px\"></tr>\r\n" + "    <tr>\r\n"
            + "      <td height=\"80px\" width=\"600px\" bgcolor=\"#030621\" align=\"center\">\r\n"
            + "        <p style=\"font-size:14px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif; color: #ffffff;\">Copyrights 2022 Invicta Innovations. All rights reserved.</p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n" + "  </td>\r\n"
            + "  </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "</body>");

  }

  @Async
  @Transactional
  public void sendVerifyEmailCorporate(String email, String token) {
    emailClintService.sendHtmlMail(email, "Email Verification",
        "<body style=\"background-color:#fff; margin:0;padding:0;\"><script type=\"text/javascript\" src=\"https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=uWQYkQcUkiR3yTzQOvhyHhfMCdJqQmBI4bf9gj6pwuCpOyq9WurNHCBeyn0DShbiTt6k_61S9hUXXwmct_ZXvQYVh_ekEZ_3WO0ySS1Bhrr8E3U-g2enfvI3vermQ_mxhr16DtKdX1zQD_mohdxzwe_BNcObs3xAUM9eyES6grwRql3ZdOaDZB1RbzQxU7eszw1oHiqZ0XQLjFsXubYdm3plic1wyOPck9k73lZXXtn_5mfv60T5cQHHpQz7GtDCt_NHeEAMWJlnGuvBW4DzipVJ8GFQV2Az8wNWPvTRviPatf-HPO4wnGWPxilcQriHzRuYzuyxs4kI2gJP-oeUdnfLjEhi59sUxI01yLPXbhQvWKPSqktKdETkhad_cEtq0XZBRu3W6fn7sbqCOwS7vJpNcNThGB5TYgRUxm9rPV5fu8PbNrEqzrbe39iNrqVk3N6oVzKz0oN35mVdoPjp89iEKoLtuHv4VtIE3D0q8NMDsyZBbRKD8gCv9sIjCZJvd0eK1KLToe3PBml8YTQGK6yacmP_BVHNmlIcOwS-VTaSwluyLP1Zi_O36SUQrsSQ5vKcNaLkjJ2sN-p4TbPSmd45uwEThn9JrMr3_FCCm5RC7YKb9yOWdKDUgvz5iipzO_lTxU5njmdmiAgCwhh5NkOGAs2o6rBI_KG9Lo34mi0NfleJND1OhGuw75ap92RX9BkDm53VQ1sZv-21wAkHwyFgMxodvPUQ2GTqkvviWlp7L-iIpC8AQIGxbGFP5a7EExsSaQUdcGgkDH8VPv7mRT8pkamBV-jn3REy0G8YFpryC5AdnwGBlMjlPjqZrAQHwFhWf-HSZL1XeLPa-0fuaIohM6vldYZbC22bbnO2WAiN9K5TBtvA4cjgctFvHdWD2k_dLLFg-uPiMTH0y99Lrs8m5vQteU3CXGyIHfDjPZWU2eoqCNr_Q6GxdNR_iHdJAK9bKmPdp8921Y0JTxXJJ0uI-cfCR9w7uZYgJGX-tVd0q-GZX93C4D-CRzAVm_tck9ZPuwB94wzZfwrSM0UgeZFtxc5AmhkiS9FnS7H8jeFHpOdmwaTehGLXE0lYAs7oS5AC6CRjJaji0sowlF9_cauPrTYaw5oSjqBGYN95WCZSQ1BBCrL3wT0E0GkRkPiYHTEpD7hNVlkt-l-9b4aJe25KMF3pE4WCFrLTEiR0Yon_5oKCX2ApAH7iEKWZT30u__qAvfy79z0IfDbfZe2uGQp-a_HwGUOG6Mt7ZRFlD-1mu0Bp4YSBKg-TVdo-dPSwy8Z4S5cvI4d9ghh_DoNnQpB1esqMw0P8U1flsTrE5AvLUjG2Heok8ApImTSPnyaR\" nonce=\"2d9d35df038e8914d8b3ca29bf3da3e2\" charset=\"UTF-8\"></script>\r\n"
            + "  <table class=\"main\" align=\"center\" width=\"600px\" style=\"background-color: #ffffff;\">\r\n"
            + "  <tbody>\r\n" + "    <tr>\r\n" + "    <td>\r\n"
            + "    <table class=\"title\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "     <tr>\r\n" + "       <td width=\"75px\">\r\n"
            + "         <img style=\"width: 56px; padding: 5px;\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681390/9baceaa7eb7ddf952f5a8c76ba6cae947421b9cbabb4b14d3a9fd4201e4b2dd4/280x280_middle.jpg\"/>\r\n"
            + "       </td>\r\n" + "       <td>\r\n"
            + "         <div> <span style=\"font-weight:400;font-size:24px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#000000;\"><strong>Fleet Management</strong></span> </div>\r\n"
            + "       </td>\r\n" + "     </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"illustration\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td>\r\n"
            + "        <img style=\"width: 260px; height: 220px; object-fit: cover\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681394/08cce7223850b4e99abcee6b4968625871aa764e592f74ffdd7ddfe9a0f3bf2f/280x280_middle.jpg\"/>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"content\" width=\"500px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td align=\"center\">\r\n"
            + "        <p><span style=\"font-size:18px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;font-weight: bold;\">Autorize your SignUp using the One Time Password below:</span></p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "    <tr height=\"80px\">\r\n"
            + "      <td align=\"center\">\r\n"
            + "        <span style=\"font-weight:400;font-size:35px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#008175;\"><strong>"
            + token + "</strong></span>\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
            + "      <td align=\"center\">\r\n"
            + "        <p><span style=\"font-size:15px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif\">This activation code expires in 10 minutes</span></p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"footer\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr height=\"30px\"></tr>\r\n" + "    <tr>\r\n"
            + "      <td height=\"80px\" width=\"600px\" bgcolor=\"#030621\" align=\"center\">\r\n"
            + "        <p style=\"font-size:14px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif; color: #ffffff;\">� 2022 Invicta Innovations. All rights reserved.</p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n" + "  </td>\r\n"
            + "  </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "</body>");

  }

  @Async
  @Transactional
  public void sendDeactivateStatusEmail(String email, User user) {
    emailClintService.sendHtmlMail(email, "Your Account is Deactivated",
        "<body style=\"background-color: #f4f4f5;\">\r\n"
            + "<table cellpadding=\"0\" cellspacing=\"0\" style=\"width: 100%; height: 100%; background-color: #f4f4f5; text-align: center;\">\r\n"
            + "<tbody><tr>\r\n" + "<td style=\"text-align: center;\">\r\n"
            + "<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"body\" style=\"background-color: #fff; width: 100%; max-width: 680px; height: 100%;\">\r\n"
            + "<tbody><tr>\r\n" + "<td>\r\n"
            + "<table bgcolor=\"#e1e1e1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"page-center\" style=\"text-align: left; padding-bottom: 88px; width: 100%; padding-left: 120px; padding-right: 120px;\">\r\n"
            + "<tbody><tr>\r\n" + "<td style=\"padding-top: 24px;\">\r\n"
            + "<img src=\"https://d1pgqke3goo8l6.cloudfront.net/wRMe5oiRRqYamUFBvXEw_logo.png\" style=\"width: 56px;\">\r\n"
            + "</td>\r\n" + "</tr>\r\n" + "<tr>\r\n"
            + "<td colspan=\"2\" style=\"padding-top: 40px; -ms-text-size-adjust: 100%; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: 100%; color: #000000; font-family: 'Postmates Std', 'Helvetica', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif; font-size: 48px; font-smoothing: always; font-style: normal; font-weight: 600; letter-spacing: -2.6px; line-height: 52px; mso-line-height-rule: exactly; text-decoration: none;\">Your Account is Deactivated</td>\r\n"
            + "</tr>\r\n" + "<tr>\r\n" + "<td style=\"padding-top: 20px;\">\r\n"
            + "<table cellpadding=\"0\" cellspacing=\"0\" style=\"width: 100%\">\r\n"
            + "<tbody><tr>\r\n"
            + "<td style=\"width: 100%; height: 1px; max-height: 1px; background-color: #d9dbe0; opacity: 0.81\"></td>\r\n"
            + "</tr>\r\n" + "</tbody></table>\r\n" + "</td>\r\n" + "</tr>\r\n" + "<tr>\r\n"
            + "<td style=\"-ms-text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: 100%; color: #9095a2; font-family: 'Postmates Std', 'Helvetica', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif; font-size: 16px; font-smoothing: always; font-style: normal; font-weight: 400; letter-spacing: -0.18px; line-height: 24px; mso-line-height-rule: exactly; text-decoration: none; vertical-align: top; width: 100%;\">\r\n"
            + "                                      You're receiving this e-mail because your Account is Deactivated.\r\n"
            + "                                    </td>\r\n" + "</tr>\r\n" + "<tr>\r\n"
            + "<td style=\"padding-top: 10px; -ms-text-size-adjust: 100%; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: 100%; color: #9095a2; font-family: 'Postmates Std', 'Helvetica', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif; font-size: 16px; font-smoothing: always; font-style: normal; font-weight: 400; letter-spacing: -0.18px; line-height: 24px; mso-line-height-rule: exactly; text-decoration: none; vertical-align: top; width: 100%;\">\r\n"
            + "                                      More Details Contact Our Admin : "
            + "admin@gmail.com" + "\r\n" + "                                    </td>\r\n"
            + "</tr>\r\n" + "<tr>\r\n" + "</tbody></table>\r\n" + "</td>\r\n" + "</tr>\r\n"
            + "</tbody></table>\r\n" + "</body>");

  }

  @Async
  @Transactional
  public void sendBranchAdminAllocation(String email, BranchAdmin branchAdmin) {
    emailClintService.sendHtmlMail(email, "Branch Admin Allocation",
        "<body style=\"background-color:#fff; margin:0;padding:0;\"><script type=\"text/javascript\" src=\"https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=LL79vB1YOCJXXtYsRF2jxb_IoNto3sBLY02_vIhltRUJ1UTabezRuBVbNPxb0oY-wh14zCYeY8tl-y9t_J0SqLzwCHjTSk02X1_lFoFaVwMAgHBfZTX97v2r0InW6DEPTj5OLDxdiEIoJ088UJHgHy_HuaWLONtn87yuRSMSusErPq5rFm4jSDN6fz7WMgJDVVw7cZMm8JiboT7DFOj6sJ6cHRktwYs0wSI1VQPfnLcRhyuraSYgoNZ_myNK_pQ6c5q63ny_2PtKSBXUrMaQ0jtvpPeQaktK_JwBnT8u7V9WJAzKejmfEBFUtvugsAJ5_rGaasF64uWnhKtu_YLsbDyFmm-nGhEn5mMoMOTh_XMl8I2lMrVUy4aclozRs26LwhUtpdqY2wouWeGrMz1NGTzre6NEp9-cFig4QXJqIcKT1-PR_KHcXiVCeg7yA0P922xEHlLHz71MqsKzqyJzebMFdCsRNyDl9N0kbXYNCCBFUQ_VZTDGV0B6s9LO7jOOshqH7pQapIGjkXPcJrtqx0X-hYLUqq_nyURey6ai33RZ4Gi8tnCEf-H4oCG8I847dcGDU3ZAyEylrBRAS4ZQal2MtkZeOqD9Nte6izD8ol_k6a9Cy11Msm32z4TNVTrHV0YQ_w2kVEJ3OTFJFHnjLE9K03M5R5XvGfENPDCwkHuWUmGf-r68Oucx4CB8CtFTG1NPfACvc-UcFXhLid95iU78lfAAgEyht9irP4ZXWepy55LBqoBjU9CYi4gAsB9Y50qZGw5gHbzl8_SMJVBF38eX6aGdQP5pawtzA7U0ptaQBpaXfrdD9N8YSP6fxptrJqaXljZVrAbqLhCmb7td-qlh4eWhxsGNBpLk22zCNyB63KX2uaFDolffUCBem-L4FtxyBbvyn_WX6gD6MGihVEZNPW2ha5LZ3MFJvhgXxuf4janUExKiMKQ3TT9MXam2UHuBH4HoWYSi_DmNqY0ylOlBxQWLEeWvdTGpkIn0L4i3YBvAoMs5IpHUK9ipu8F7lj-Vs1r0w3CVkZLbnGR6xEosogfGxhG8SEl8cV-xILG6B6H_AajWUq-W2Oyl1QZS5VUuqiNdCo9Ar3LwZ89kyBAzBc9-3Py2H8TeZMm-x1QDP70KH0xJgqAzS9xU36X5iqupNtSHwiTL2V5msuUvMyjWeeEXxaZrODMruVw30FHUNfxVjOcMPXeZS7KBHrNDtBOa3pAOHuZJ7U3Mscafvr1PxMSS0djpi-2IvnXNCL9OBDC8Zy0AVD4MQ3mNkDTVnSCDgduJadCzeB0sJGzWpRhUgCWnpU9M35Rnds8-Qa-PbpfYJjw_mph8QXF6ZwWULVjtEDD6ZdfReIWSoOU6qA\" nonce=\"026f2d499fa224d04b8f563310f3d952\" charset=\"UTF-8\"></script>\r\n"
            + "  <table class=\"main\" align=\"center\" width=\"600px\" style=\"background-color: #ffffff;\">\r\n"
            + "  <tbody>\r\n" + "    <tr>\r\n" + "    <td>\r\n"
            + "    <table class=\"title\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "     <tr>\r\n" + "       <td width=\"75px\">\r\n"
            + "         <img style=\"width: 56px; padding: 5px;\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681390/9baceaa7eb7ddf952f5a8c76ba6cae947421b9cbabb4b14d3a9fd4201e4b2dd4/280x280_middle.jpg\"/>\r\n"
            + "       </td>\r\n" + "       <td>\r\n"
            + "         <div> <span style=\"font-weight:400;font-size:24px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#000000;\"><strong>Fleet Management</strong></span> </div>\r\n"
            + "       </td>\r\n" + "     </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"illustration\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td>\r\n"
            + "        <img style=\"width: 320px; height: 240px; object-fit: cover\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681392/343c976cd02b4fb97e2f0c385b22bb9be48868922816583b50088332adb7041b/280x280_middle.jpg\"/>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"content\" width=\"500px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td>\r\n"
            + "        <span style=\"font-weight:400;font-size:35px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#141b55;\"><strong>Congratulations !</strong></span>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n" + "      <td>\r\n"
            + "        <p><span style=\"font-size:20px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif\">You have been assigned as Branch Admin of "
            + branchAdmin.getBranch().getBranchName() + " Branch.</span></p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"footer\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr height=\"40px\"></tr>\r\n" + "    <tr>\r\n"
            + "      <td height=\"80px\" width=\"600px\" bgcolor=\"#030621\" align=\"center\">\r\n"
            + "        <p style=\"font-size:14px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif; color: #ffffff;\">� 2022 Invicta Innovations. All rights reserved.</p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n" + "  </td>\r\n"
            + "  </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "</body>");

  }

  @Async
  @Transactional
  public void sendDeliveryBoyBranchUpdateEmail(DeliveryBoyBranchUpdateDto deliveryBoyBranchUpdateDto) {
    emailClintService.sendHtmlMail(deliveryBoyBranchUpdateDto.getEmail(), "Branch Update Mail",
        "You are assigned to " + deliveryBoyBranchUpdateDto.getBranchName() + " branch");
  }

  @Async
  @Transactional
  public void sendDeliveryBoyAllocationEmail(String email, DeliveryBoy deliveryBoy) {
    emailClintService.sendHtmlMail(email, "Driver Allocation ", "<!DOCTYPE html>\r\n" + "<html\r\n"
        + "    xmlns:v=\"urn:schemas-microsoft-com:vml\"\r\n"
        + "    xmlns:o=\"urn:schemas-microsoft-com:office:office\"\r\n" + "    lang=\"en\"\r\n"
        + ">\r\n" + "    <head>\r\n" + "        <title></title>\r\n"
        + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
        + "        <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\r\n"
        + "        <!--[if mso\r\n" + "            ]><xml\r\n"
        + "                ><o:OfficeDocumentSettings\r\n"
        + "                    ><o:PixelsPerInch>96</o:PixelsPerInch\r\n"
        + "                    ><o:AllowPNG /></o:OfficeDocumentSettings></xml\r\n"
        + "        ><![endif]-->\r\n" + "        <!--[if !mso]><!-->\r\n" + "        <link\r\n"
        + "            href=\"https://fonts.googleapis.com/css?family=Roboto\"\r\n"
        + "            rel=\"stylesheet\"\r\n" + "            type=\"text/css\"\r\n"
        + "        />\r\n" + "        <!--<![endif]-->\r\n" + "        <style>\r\n"
        + "            * {\r\n" + "                box-sizing: border-box;\r\n"
        + "            }\r\n" + "            body {\r\n" + "                margin: 0;\r\n"
        + "                padding: 0;\r\n" + "            }\r\n"
        + "            a[x-apple-data-detectors] {\r\n"
        + "                color: inherit !important;\r\n"
        + "                text-decoration: inherit !important;\r\n" + "            }\r\n"
        + "            #MessageViewBody a {\r\n" + "                color: inherit;\r\n"
        + "                text-decoration: none;\r\n" + "            }\r\n" + "            p {\r\n"
        + "                line-height: inherit;\r\n" + "            }\r\n"
        + "            .desktop_hide,\r\n" + "            .desktop_hide table {\r\n"
        + "                mso-hide: all;\r\n" + "                display: none;\r\n"
        + "                max-height: 0;\r\n" + "                overflow: hidden;\r\n"
        + "            }\r\n" + "            @media (max-width: 720px) {\r\n"
        + "                .image_block img.big,\r\n" + "                .row-content {\r\n"
        + "                    width: 100% !important;\r\n" + "                }\r\n"
        + "                .mobile_hide {\r\n" + "                    display: none;\r\n"
        + "                }\r\n" + "                .stack .column {\r\n"
        + "                    width: 100%;\r\n" + "                    display: block;\r\n"
        + "                }\r\n" + "                .mobile_hide {\r\n"
        + "                    min-height: 0;\r\n" + "                    max-height: 0;\r\n"
        + "                    max-width: 0;\r\n" + "                    overflow: hidden;\r\n"
        + "                    font-size: 0;\r\n" + "                }\r\n"
        + "                .desktop_hide,\r\n" + "                .desktop_hide table {\r\n"
        + "                    display: table !important;\r\n"
        + "                    max-height: none !important;\r\n" + "                }\r\n"
        + "            }\r\n" + "        </style>\r\n" + "    </head>\r\n" + "    <body\r\n"
        + "        style=\"\r\n" + "            background-color: #fff;\r\n"
        + "            margin: 0;\r\n" + "            padding: 0;\r\n"
        + "            -webkit-text-size-adjust: none;\r\n"
        + "            text-size-adjust: none;\r\n" + "        \"\r\n" + "    >\r\n"
        + "        <table\r\n" + "            class=\"nl-container\"\r\n"
        + "            width=\"100%\"\r\n" + "            border=\"0\"\r\n"
        + "            cellpadding=\"0\"\r\n" + "            cellspacing=\"0\"\r\n"
        + "            role=\"presentation\"\r\n"
        + "            style=\"background-color: #fff\"\r\n" + "        >\r\n"
        + "            <tbody>\r\n" + "                <tr>\r\n" + "                    <td>\r\n"
        + "                        <table\r\n"
        + "                            class=\"row row-1\"\r\n"
        + "                            align=\"center\"\r\n"
        + "                            width=\"100%\"\r\n"
        + "                            border=\"0\"\r\n"
        + "                            cellpadding=\"0\"\r\n"
        + "                            cellspacing=\"0\"\r\n"
        + "                            role=\"presentation\"\r\n" + "                        >\r\n"
        + "                            <tbody>\r\n" + "                                <tr>\r\n"
        + "                                    <td>\r\n"
        + "                                        <table\r\n"
        + "                                            class=\"row-content stack\"\r\n"
        + "                                            align=\"center\"\r\n"
        + "                                            border=\"0\"\r\n"
        + "                                            cellpadding=\"0\"\r\n"
        + "                                            cellspacing=\"0\"\r\n"
        + "                                            role=\"presentation\"\r\n"
        + "                                            style=\"\r\n"
        + "                                                color: #000;\r\n"
        + "                                                width: 700px;\r\n"
        + "                                                transform: translate(-16px);\r\n"
        + "                                            \"\r\n"
        + "                                            width=\"700\"\r\n"
        + "                                        >\r\n"
        + "                                            <tbody>\r\n"
        + "                                                <tr>\r\n"
        + "                                                    <td\r\n"
        + "                                                        class=\"column column-1\"\r\n"
        + "                                                        width=\"25%\"\r\n"
        + "                                                        style=\"\r\n"
        + "                                                            font-weight: 400;\r\n"
        + "                                                            text-align: left;\r\n"
        + "                                                            vertical-align: top;\r\n"
        + "                                                            border-top: 0;\r\n"
        + "                                                            border-right: 0;\r\n"
        + "                                                            border-bottom: 0;\r\n"
        + "                                                            border-left: 0;\r\n"
        + "                                                        \"\r\n"
        + "                                                    >\r\n"
        + "                                                        <table\r\n"
        + "                                                            class=\"image_block block-2\"\r\n"
        + "                                                            width=\"100%\"\r\n"
        + "                                                            border=\"0\"\r\n"
        + "                                                            cellpadding=\"0\"\r\n"
        + "                                                            cellspacing=\"0\"\r\n"
        + "                                                            role=\"presentation\"\r\n"
        + "                                                        >\r\n"
        + "                                                            <tr>\r\n"
        + "                                                                <td\r\n"
        + "                                                                    class=\"pad\"\r\n"
        + "                                                                    style=\"\r\n"
        + "                                                                        width: 100%;\r\n"
        + "                                                                        padding-right: 0;\r\n"
        + "                                                                        padding-left: 0;\r\n"
        + "                                                                        padding-top: 5px;\r\n"
        + "                                                                        padding-bottom: 5px;\r\n"
        + "                                                                    \"\r\n"
        + "                                                                >\r\n"
        + "                                                                    <div\r\n"
        + "                                                                        class=\"alignment\"\r\n"
        + "                                                                        align=\"center\"\r\n"
        + "                                                                        style=\"\r\n"
        + "                                                                            line-height: 10px;\r\n"
        + "                                                                        \"\r\n"
        + "                                                                    >\r\n"
        + "                                                                        <img\r\n"
        + "                                                                            style=\"\r\n"
        + "                                                                                width: 60px;\r\n"
        + "                                                                            \"\r\n"
        + "                                                                            src=\"https://www.udrop.com/cache/plugins/filepreviewer/681390/9baceaa7eb7ddf952f5a8c76ba6cae947421b9cbabb4b14d3a9fd4201e4b2dd4/280x280_middle.jpg\"\r\n"
        + "                                                                        />\r\n"
        + "                                                                    </div>\r\n"
        + "                                                                </td>\r\n"
        + "                                                            </tr>\r\n"
        + "                                                        </table>\r\n"
        + "                                                    </td>\r\n"
        + "                                                    <td\r\n"
        + "                                                        class=\"column column-2\"\r\n"
        + "                                                        width=\"75%\"\r\n"
        + "                                                        style=\"\r\n"
        + "                                                            font-weight: 400;\r\n"
        + "                                                            text-align: left;\r\n"
        + "                                                            vertical-align: top;\r\n"
        + "                                                            border-top: 0;\r\n"
        + "                                                            border-right: 0;\r\n"
        + "                                                            border-bottom: 0;\r\n"
        + "                                                            border-left: 0;\r\n"
        + "                                                        \"\r\n"
        + "                                                    >\r\n"
        + "                                                        <table\r\n"
        + "                                                            class=\"text_block block-2\"\r\n"
        + "                                                            width=\"100%\"\r\n"
        + "                                                            border=\"0\"\r\n"
        + "                                                            cellpadding=\"0\"\r\n"
        + "                                                            cellspacing=\"0\"\r\n"
        + "                                                            role=\"presentation\"\r\n"
        + "                                                            style=\"\r\n"
        + "                                                                word-break: break-word;\r\n"
        + "                                                            \"\r\n"
        + "                                                        >\r\n"
        + "                                                            <tr>\r\n"
        + "                                                                <td\r\n"
        + "                                                                    class=\"pad\"\r\n"
        + "                                                                    style=\"\r\n"
        + "                                                                        padding-top: 15px;\r\n"
        + "                                                                        padding-right: 10px;\r\n"
        + "                                                                        padding-bottom: 15px;\r\n"
        + "                                                                        padding-left: 10px;\r\n"
        + "                                                                    \"\r\n"
        + "                                                                >\r\n"
        + "                                                                    <div\r\n"
        + "                                                                        style=\"\r\n"
        + "                                                                            font-family: Tahoma,\r\n"
        + "                                                                                Verdana,\r\n"
        + "                                                                                sans-serif;\r\n"
        + "                                                                        \"\r\n"
        + "                                                                    >\r\n"
        + "                                                                        <div\r\n"
        + "                                                                            class=\"txtTinyMce-wrapper\"\r\n"
        + "                                                                            style=\"\r\n"
        + "                                                                                font-size: 14px;\r\n"
        + "                                                                                font-family: Roboto,\r\n"
        + "                                                                                    Tahoma,\r\n"
        + "                                                                                    Verdana,\r\n"
        + "                                                                                    Segoe,\r\n"
        + "                                                                                    sans-serif;\r\n"
        + "                                                                                mso-line-height-alt: 16.8px;\r\n"
        + "                                                                                color: #000000;\r\n"
        + "                                                                                line-height: 2;\r\n"
        + "                                                                                transform: translate(\r\n"
        + "                                                                                    -50px\r\n"
        + "                                                                                );\r\n"
        + "                                                                            \"\r\n"
        + "                                                                        >\r\n"
        + "                                                                            <p\r\n"
        + "                                                                                style=\"\r\n"
        + "                                                                                    margin: 0;\r\n"
        + "                                                                                    font-size: 14px;\r\n"
        + "                                                                                \"\r\n"
        + "                                                                            >\r\n"
        + "                                                                                <span\r\n"
        + "                                                                                    style=\"\r\n"
        + "                                                                                        font-size: 24px;\r\n"
        + "                                                                                    \"\r\n"
        + "                                                                                    ><strong\r\n"
        + "                                                                                        >Fleet\r\n"
        + "                                                                                        App</strong\r\n"
        + "                                                                                    ></span\r\n"
        + "                                                                                >\r\n"
        + "                                                                            </p>\r\n"
        + "                                                                        </div>\r\n"
        + "                                                                    </div>\r\n"
        + "                                                                </td>\r\n"
        + "                                                            </tr>\r\n"
        + "                                                        </table>\r\n"
        + "                                                    </td>\r\n"
        + "                                                </tr>\r\n"
        + "                                            </tbody>\r\n"
        + "                                        </table>\r\n"
        + "                                    </td>\r\n"
        + "                                </tr>\r\n" + "                            </tbody>\r\n"
        + "                        </table>\r\n" + "                        <table\r\n"
        + "                            class=\"row row-2\"\r\n"
        + "                            align=\"center\"\r\n"
        + "                            width=\"100%\"\r\n"
        + "                            border=\"0\"\r\n"
        + "                            cellpadding=\"0\"\r\n"
        + "                            cellspacing=\"0\"\r\n"
        + "                            role=\"presentation\"\r\n" + "                        >\r\n"
        + "                            <tbody>\r\n" + "                                <tr>\r\n"
        + "                                    <td>\r\n"
        + "                                        <table\r\n"
        + "                                            class=\"row-content\"\r\n"
        + "                                            align=\"center\"\r\n"
        + "                                            border=\"0\"\r\n"
        + "                                            cellpadding=\"0\"\r\n"
        + "                                            cellspacing=\"0\"\r\n"
        + "                                            role=\"presentation\"\r\n"
        + "                                            style=\"color: #000; width: 700px\"\r\n"
        + "                                            width=\"700\"\r\n"
        + "                                        >\r\n"
        + "                                            <tbody>\r\n"
        + "                                                <tr>\r\n"
        + "                                                    <td\r\n"
        + "                                                        class=\"column column-1\"\r\n"
        + "                                                        width=\"100%\"\r\n"
        + "                                                        style=\"\r\n"
        + "                                                            font-weight: 400;\r\n"
        + "                                                            text-align: left;\r\n"
        + "                                                            vertical-align: top;\r\n"
        + "                                                            padding-top: 5px;\r\n"
        + "                                                            padding-bottom: 5px;\r\n"
        + "                                                            border-top: 0;\r\n"
        + "                                                            border-right: 0;\r\n"
        + "                                                            border-bottom: 0;\r\n"
        + "                                                            border-left: 0;\r\n"
        + "                                                        \"\r\n"
        + "                                                    >\r\n"
        + "                                                        <table\r\n"
        + "                                                            class=\"image_block block-1\"\r\n"
        + "                                                            width=\"100%\"\r\n"
        + "                                                            border=\"0\"\r\n"
        + "                                                            cellpadding=\"0\"\r\n"
        + "                                                            cellspacing=\"0\"\r\n"
        + "                                                            role=\"presentation\"\r\n"
        + "                                                        >\r\n"
        + "                                                            <tr>\r\n"
        + "                                                                <td\r\n"
        + "                                                                    class=\"pad\"\r\n"
        + "                                                                    style=\"\r\n"
        + "                                                                        width: 100%;\r\n"
        + "                                                                        padding-right: 0;\r\n"
        + "                                                                        padding-left: 0;\r\n"
        + "                                                                    \"\r\n"
        + "                                                                >\r\n"
        + "                                                                    <div\r\n"
        + "                                                                        class=\"alignment\"\r\n"
        + "                                                                        align=\"center\"\r\n"
        + "                                                                        style=\"\r\n"
        + "                                                                            line-height: 10px;\r\n"
        + "                                                                        \"\r\n"
        + "                                                                    >\r\n"
        + "                                                                        <img\r\n"
        + "                                                                            src=\"https://www.udrop.com/cache/plugins/filepreviewer/681391/c218c890aacdfe9ac01aad33eb8dd5ad520f37ce125aa4091ae5f64d6d4b3d39/280x280_middle.jpg\"\r\n"
        + "                                                                        />\r\n"
        + "                                                                    </div>\r\n"
        + "                                                                </td>\r\n"
        + "                                                            </tr>\r\n"
        + "                                                        </table>\r\n"
        + "                                                    </td>\r\n"
        + "                                                </tr>\r\n"
        + "                                            </tbody>\r\n"
        + "                                        </table>\r\n"
        + "                                    </td>\r\n"
        + "                                </tr>\r\n" + "                            </tbody>\r\n"
        + "                        </table>\r\n" + "                        <table\r\n"
        + "                            class=\"row row-3\"\r\n"
        + "                            align=\"center\"\r\n"
        + "                            width=\"100%\"\r\n"
        + "                            border=\"0\"\r\n"
        + "                            cellpadding=\"0\"\r\n"
        + "                            cellspacing=\"0\"\r\n"
        + "                            role=\"presentation\"\r\n" + "                        >\r\n"
        + "                            <tbody>\r\n" + "                                <tr>\r\n"
        + "                                    <td>\r\n"
        + "                                        <table\r\n"
        + "                                            class=\"row-content stack\"\r\n"
        + "                                            align=\"center\"\r\n"
        + "                                            border=\"0\"\r\n"
        + "                                            cellpadding=\"0\"\r\n"
        + "                                            cellspacing=\"0\"\r\n"
        + "                                            role=\"presentation\"\r\n"
        + "                                            style=\"\r\n"
        + "                                                color: #000;\r\n"
        + "                                                border-radius: 0;\r\n"
        + "                                                width: 700px;\r\n"
        + "                                            \"\r\n"
        + "                                            width=\"700\"\r\n"
        + "                                        >\r\n"
        + "                                            <tbody>\r\n"
        + "                                                <tr>\r\n"
        + "                                                    <td\r\n"
        + "                                                        class=\"column column-1\"\r\n"
        + "                                                        width=\"100%\"\r\n"
        + "                                                        style=\"\r\n"
        + "                                                            font-weight: 400;\r\n"
        + "                                                            text-align: left;\r\n"
        + "                                                            vertical-align: top;\r\n"
        + "                                                            padding-top: 5px;\r\n"
        + "                                                            padding-bottom: 5px;\r\n"
        + "                                                            border-top: 0;\r\n"
        + "                                                            border-right: 0;\r\n"
        + "                                                            border-bottom: 0;\r\n"
        + "                                                            border-left: 0;\r\n"
        + "                                                        \"\r\n"
        + "                                                    >\r\n"
        + "                                                        <table\r\n"
        + "                                                            class=\"text_block block-1\"\r\n"
        + "                                                            width=\"100%\"\r\n"
        + "                                                            border=\"0\"\r\n"
        + "                                                            cellpadding=\"0\"\r\n"
        + "                                                            cellspacing=\"0\"\r\n"
        + "                                                            role=\"presentation\"\r\n"
        + "                                                            style=\"\r\n"
        + "                                                                word-break: break-word;\r\n"
        + "                                                            \"\r\n"
        + "                                                        >\r\n"
        + "                                                            <tr>\r\n"
        + "                                                                <td\r\n"
        + "                                                                    class=\"pad\"\r\n"
        + "                                                                    style=\"\r\n"
        + "                                                                        padding-top: 15px;\r\n"
        + "                                                                        padding-left: 50px;\r\n"
        + "                                                                    \"\r\n"
        + "                                                                >\r\n"
        + "                                                                    <div\r\n"
        + "                                                                        style=\"\r\n"
        + "                                                                            font-family: Tahoma,\r\n"
        + "                                                                                Verdana,\r\n"
        + "                                                                                sans-serif;\r\n"
        + "                                                                        \"\r\n"
        + "                                                                    >\r\n"
        + "                                                                        <div\r\n"
        + "                                                                            class=\"txtTinyMce-wrapper\"\r\n"
        + "                                                                            style=\"\r\n"
        + "                                                                                font-size: 14px;\r\n"
        + "                                                                                font-family: Roboto,\r\n"
        + "                                                                                    Tahoma,\r\n"
        + "                                                                                    Verdana,\r\n"
        + "                                                                                    Segoe,\r\n"
        + "                                                                                    sans-serif;\r\n"
        + "                                                                                mso-line-height-alt: 16.8px;\r\n"
        + "                                                                                color: #141b55;\r\n"
        + "                                                                                line-height: 1.2;\r\n"
        + "                                                                            \"\r\n"
        + "                                                                        >\r\n"
        + "                                                                            <p\r\n"
        + "                                                                                style=\"\r\n"
        + "                                                                                    margin: 0;\r\n"
        + "                                                                                    font-size: 14px;\r\n"
        + "                                                                                \"\r\n"
        + "                                                                            >\r\n"
        + "                                                                                <span\r\n"
        + "                                                                                    style=\"\r\n"
        + "                                                                                        font-size: 42px;\r\n"
        + "                                                                                    \"\r\n"
        + "                                                                                    ><strong\r\n"
        + "                                                                                        >Congratulations\r\n"
        + "                                                                                        !</strong\r\n"
        + "                                                                                    ></span\r\n"
        + "                                                                                >\r\n"
        + "                                                                            </p>\r\n"
        + "                                                                        </div>\r\n"
        + "                                                                    </div>\r\n"
        + "                                                                </td>\r\n"
        + "                                                            </tr>\r\n"
        + "                                                        </table>\r\n"
        + "                                                    </td>\r\n"
        + "                                                </tr>\r\n"
        + "                                            </tbody>\r\n"
        + "                                        </table>\r\n"
        + "                                    </td>\r\n"
        + "                                </tr>\r\n" + "                            </tbody>\r\n"
        + "                        </table>\r\n" + "                        <table\r\n"
        + "                            class=\"row row-4\"\r\n"
        + "                            align=\"center\"\r\n"
        + "                            width=\"100%\"\r\n"
        + "                            border=\"0\"\r\n"
        + "                            cellpadding=\"0\"\r\n"
        + "                            cellspacing=\"0\"\r\n"
        + "                            role=\"presentation\"\r\n" + "                        >\r\n"
        + "                            <tbody>\r\n" + "                                <tr>\r\n"
        + "                                    <td>\r\n"
        + "                                        <table\r\n"
        + "                                            class=\"row-content stack\"\r\n"
        + "                                            align=\"center\"\r\n"
        + "                                            border=\"0\"\r\n"
        + "                                            cellpadding=\"0\"\r\n"
        + "                                            cellspacing=\"0\"\r\n"
        + "                                            role=\"presentation\"\r\n"
        + "                                            style=\"\r\n"
        + "                                                color: #000;\r\n"
        + "                                                border-radius: 0;\r\n"
        + "                                                width: 680px;\r\n"
        + "                                            \"\r\n"
        + "                                            width=\"680\"\r\n"
        + "                                        >\r\n"
        + "                                            <tbody>\r\n"
        + "                                                <tr>\r\n"
        + "                                                    <td\r\n"
        + "                                                        class=\"column column-1\"\r\n"
        + "                                                        width=\"100%\"\r\n"
        + "                                                        style=\"\r\n"
        + "                                                            font-weight: 400;\r\n"
        + "                                                            text-align: left;\r\n"
        + "                                                            vertical-align: top;\r\n"
        + "                                                            padding-top: 5px;\r\n"
        + "                                                            padding-bottom: 5px;\r\n"
        + "                                                            border-top: 0;\r\n"
        + "                                                            border-right: 0;\r\n"
        + "                                                            border-bottom: 0;\r\n"
        + "                                                            border-left: 0;\r\n"
        + "                                                        \"\r\n"
        + "                                                    >\r\n"
        + "                                                        <table\r\n"
        + "                                                            class=\"text_block block-1\"\r\n"
        + "                                                            width=\"100%\"\r\n"
        + "                                                            border=\"0\"\r\n"
        + "                                                            cellpadding=\"0\"\r\n"
        + "                                                            cellspacing=\"0\"\r\n"
        + "                                                            role=\"presentation\"\r\n"
        + "                                                            style=\"\r\n"
        + "                                                                word-break: break-word;\r\n"
        + "                                                            \"\r\n"
        + "                                                        >\r\n"
        + "                                                            <tr>\r\n"
        + "                                                                <td\r\n"
        + "                                                                    class=\"pad\"\r\n"
        + "                                                                    style=\"\r\n"
        + "                                                                        padding-top: 10px;\r\n"
        + "                                                                        padding-right: 10px;\r\n"
        + "                                                                        padding-bottom: 40px;\r\n"
        + "                                                                        padding-left: 50px;\r\n"
        + "                                                                    \"\r\n"
        + "                                                                >\r\n"
        + "                                                                    <div\r\n"
        + "                                                                        style=\"\r\n"
        + "                                                                            font-family: Tahoma,\r\n"
        + "                                                                                Verdana,\r\n"
        + "                                                                                sans-serif;\r\n"
        + "                                                                        \"\r\n"
        + "                                                                    >\r\n"
        + "                                                                        <div\r\n"
        + "                                                                            class=\"txtTinyMce-wrapper\"\r\n"
        + "                                                                            style=\"\r\n"
        + "                                                                                font-size: 14px;\r\n"
        + "                                                                                font-family: Roboto,\r\n"
        + "                                                                                    Tahoma,\r\n"
        + "                                                                                    Verdana,\r\n"
        + "                                                                                    Segoe,\r\n"
        + "                                                                                    sans-serif;\r\n"
        + "                                                                                mso-line-height-alt: 16.8px;\r\n"
        + "                                                                                color: #000000;\r\n"
        + "                                                                                line-height: 1.2;\r\n"
        + "                                                                            \"\r\n"
        + "                                                                        >\r\n"
        + "                                                                            <p\r\n"
        + "                                                                                style=\"\r\n"
        + "                                                                                    margin: 0;\r\n"
        + "                                                                                    font-size: 14px;\r\n"
        + "                                                                                \"\r\n"
        + "                                                                            >\r\n"
        + "                                                                                <span\r\n"
        + "                                                                                    style=\"\r\n"
        + "                                                                                        font-size: 22px;\r\n"
        + "                                                                                    \"\r\n"
        + "                                                                                    >You\r\n"
        + "                                                                                    have\r\n"
        + "                                                                                    been\r\n"
        + "                                                                                    assigned\r\n"
        + "                                                                                    as\r\n"
        + "                                                                                    a\r\n"
        + "                                                                                    driver\r\n"
        + "                                                                                    to\r\n"
        + deliveryBoy.getBranch().getBranchName()
        + "                                                                                    Colombo\r\n"
        + "                                                                                    Branch.</span\r\n"
        + "                                                                                >\r\n"
        + "                                                                            </p>\r\n"
        + "                                                                        </div>\r\n"
        + "                                                                    </div>\r\n"
        + "                                                                </td>\r\n"
        + "                                                            </tr>\r\n"
        + "                                                        </table>\r\n"
        + "                                                    </td>\r\n"
        + "                                                </tr>\r\n"
        + "                                            </tbody>\r\n"
        + "                                        </table>\r\n"
        + "                                    </td>\r\n"
        + "                                </tr>\r\n" + "                            </tbody>\r\n"
        + "                        </table>\r\n" + "                        <table\r\n"
        + "                            class=\"row row-5\"\r\n"
        + "                            align=\"center\"\r\n"
        + "                            width=\"100%\"\r\n"
        + "                            border=\"0\"\r\n"
        + "                            cellpadding=\"0\"\r\n"
        + "                            cellspacing=\"0\"\r\n"
        + "                            role=\"presentation\"\r\n" + "                        >\r\n"
        + "                            <tbody>\r\n" + "                                <tr>\r\n"
        + "                                    <td>\r\n"
        + "                                        <table\r\n"
        + "                                            class=\"row-content stack\"\r\n"
        + "                                            align=\"center\"\r\n"
        + "                                            border=\"0\"\r\n"
        + "                                            cellpadding=\"0\"\r\n"
        + "                                            cellspacing=\"0\"\r\n"
        + "                                            role=\"presentation\"\r\n"
        + "                                            style=\"\r\n"
        + "                                                color: #000;\r\n"
        + "                                                border-radius: 0;\r\n"
        + "                                                width: 700px;\r\n"
        + "                                            \"\r\n"
        + "                                            width=\"700\"\r\n"
        + "                                        >\r\n"
        + "                                            <tbody>\r\n"
        + "                                                <tr>\r\n"
        + "                                                    <td\r\n"
        + "                                                        class=\"column column-1\"\r\n"
        + "                                                        width=\"100%\"\r\n"
        + "                                                        style=\"\r\n"
        + "                                                            font-weight: 400;\r\n"
        + "                                                            text-align: left;\r\n"
        + "                                                            vertical-align: top;\r\n"
        + "                                                            padding-top: 5px;\r\n"
        + "                                                            padding-bottom: 5px;\r\n"
        + "                                                            border-top: 0;\r\n"
        + "                                                            border-right: 0;\r\n"
        + "                                                            border-bottom: 0;\r\n"
        + "                                                            border-left: 0;\r\n"
        + "                                                        \"\r\n"
        + "                                                    >\r\n"
        + "                                                        <table\r\n"
        + "                                                            class=\"text_block block-1\"\r\n"
        + "                                                            width=\"100%\"\r\n"
        + "                                                            border=\"0\"\r\n"
        + "                                                            cellspacing=\"0\"\r\n"
        + "                                                            role=\"presentation\"\r\n"
        + "                                                            style=\"\r\n"
        + "                                                                word-break: break-word;\r\n"
        + "                                                            \"\r\n"
        + "                                                        >\r\n"
        + "                                                            <tr>\r\n"
        + "                                                                <td class=\"pad\">\r\n"
        + "                                                                    <div\r\n"
        + "                                                                        style=\"\r\n"
        + "                                                                            font-family: sans-serif;\r\n"
        + "                                                                        \"\r\n"
        + "                                                                    >\r\n"
        + "                                                                        <div\r\n"
        + "                                                                            class=\"txtTinyMce-wrapper\"\r\n"
        + "                                                                            style=\"\r\n"
        + "                                                                                font-size: 14px;\r\n"
        + "                                                                                mso-line-height-alt: 16.8px;\r\n"
        + "                                                                                color: #555;\r\n"
        + "                                                                                line-height: 1.2;\r\n"
        + "                                                                                font-family: Arial,\r\n"
        + "                                                                                    Helvetica\r\n"
        + "                                                                                        Neue,\r\n"
        + "                                                                                    Helvetica,\r\n"
        + "                                                                                    sans-serif;\r\n"
        + "                                                                            \"\r\n"
        + "                                                                        >\r\n"
        + "                                                                            <p\r\n"
        + "                                                                                style=\"\r\n"
        + "                                                                                    margin: 0;\r\n"
        + "                                                                                    font-size: 14px;\r\n"
        + "                                                                                    text-align: center;\r\n"
        + "                                                                                    background-color: #030621;\r\n"
        + "                                                                                    color: #ffffff;\r\n"
        + "                                                                                    padding: 40px;\r\n"
        + "                                                                                \"\r\n"
        + "                                                                            >\r\n"
        + "                                                                                �\r\n"
        + "                                                                                2022\r\n"
        + "                                                                                Invicta\r\n"
        + "                                                                                Innovations.\r\n"
        + "                                                                                All\r\n"
        + "                                                                                rights\r\n"
        + "                                                                                reserved.&nbsp;\r\n"
        + "                                                                            </p>\r\n"
        + "                                                                        </div>\r\n"
        + "                                                                    </div>\r\n"
        + "                                                                </td>\r\n"
        + "                                                            </tr>\r\n"
        + "                                                        </table>\r\n"
        + "                                                    </td>\r\n"
        + "                                                </tr>\r\n"
        + "                                            </tbody>\r\n"
        + "                                        </table>\r\n"
        + "                                    </td>\r\n"
        + "                                </tr>\r\n" + "                            </tbody>\r\n"
        + "                        </table>\r\n" + "                    </td>\r\n"
        + "                </tr>\r\n" + "            </tbody>\r\n" + "        </table>\r\n"
        + "        <div style=\"background-color: transparent\"></div>\r\n" + "    </body>\r\n"
        + "</html>\r\n" + "");

  }

  @Override
  public void sendAccountCreatedEmailForStandAlone(String mail) {
    emailClintService.sendHtmlMail(mail, "Successfully Registered",
        "<body style=\"background-color:#fff; margin:0;padding:0;\">\r\n"
            + "  <table class=\"main\" align=\"center\" width=\"600px\" style=\"background-color: #ffffff;\">\r\n"
            + "  <tbody>\r\n" + "    <tr>\r\n" + "    <td>\r\n"
            + "    <table class=\"title\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "     <tr>\r\n" + "       <td width=\"75px\">\r\n"
            + "         <img style=\"width: 56px; padding: 5px;\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681390/9baceaa7eb7ddf952f5a8c76ba6cae947421b9cbabb4b14d3a9fd4201e4b2dd4/280x280_middle.jpg\"/>\r\n"
            + "       </td>\r\n" + "       <td>\r\n"
            + "         <div> <span style=\"font-weight:400;font-size:24px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#000000;\"><strong>Fleet Management</strong></span> </div>\r\n"
            + "       </td>\r\n" + "     </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"illustration\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td>\r\n"
            + "        <img style=\"width: 320px; height: 240px; object-fit: cover\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681393/9ded61821c6851a54498d2cd7892def48b490b501857094a777a7f2816c86d12/280x280_middle.jpg\r\n"
            + "\"/>\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"content\" width=\"500px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td>\r\n"
            + "        <span style=\"font-weight:400;font-size:35px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#141b55;\"><strong>Welcome !</strong></span>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n" + "      <td>\r\n"
            + "        <p><span style=\"font-size:20px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif\">You have successfully registered Fleet Management Standalone account.</span></p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"footer\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr height=\"40px\"></tr>\r\n" + "    <tr>\r\n"
            + "      <td height=\"80px\" width=\"600px\" bgcolor=\"#030621\" align=\"center\">\r\n"
            + "        <p style=\"font-size:14px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif; color: #ffffff;\">� 2022 Invicta Innovations. All rights reserved.</p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n" + "  </td>\r\n"
            + "  </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "</body>");

  }

  @Async
  @Override
  public void sendAccountCreatedEmailForCorporate(String mail) {
    emailClintService.sendHtmlMail(mail, "Successfully Registered",
        "<body style=\"background-color:#fff; margin:0;padding:0;\">\r\n"
            + "  <table class=\"main\" align=\"center\" width=\"600px\" style=\"background-color: #ffffff;\">\r\n"
            + "  <tbody>\r\n" + "    <tr>\r\n" + "    <td>\r\n"
            + "    <table class=\"title\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "     <tr>\r\n" + "       <td width=\"75px\">\r\n"
            + "         <img style=\"width: 56px; padding: 5px;\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681390/9baceaa7eb7ddf952f5a8c76ba6cae947421b9cbabb4b14d3a9fd4201e4b2dd4/280x280_middle.jpg\"/>\r\n"
            + "       </td>\r\n" + "       <td>\r\n"
            + "         <div> <span style=\"font-weight:400;font-size:24px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#000000;\"><strong>Fleet Management</strong></span> </div>\r\n"
            + "       </td>\r\n" + "     </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"illustration\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td>\r\n"
            + "        <img style=\"width: 320px; height: 240px; object-fit: cover\" src=\"https://www.udrop.com/cache/plugins/filepreviewer/681391/c218c890aacdfe9ac01aad33eb8dd5ad520f37ce125aa4091ae5f64d6d4b3d39/280x280_middle.jpg\"/>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"content\" width=\"500px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr>\r\n" + "      <td>\r\n"
            + "        <span style=\"font-weight:400;font-size:35px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif;color:#141b55;\"><strong>Welcome !</strong></span>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n" + "      <td>\r\n"
            + "        <p><span style=\"font-size:20px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif\">You have successfully registered Fleet Management Corporate account.</span></p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n"
            + "   <table class=\"footer\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\">\r\n"
            + "    <tr height=\"40px\"></tr>\r\n" + "    <tr>\r\n"
            + "      <td height=\"80px\" width=\"600px\" bgcolor=\"#030621\" align=\"center\">\r\n"
            + "        <p style=\"font-size:14px;font-family:Roboto,Tahoma,Verdana,Segoe,sans-serif; color: #ffffff;\">� 2022 Invicta Innovations. All rights reserved.</p>\r\n"
            + "      </td>\r\n" + "    </tr>\r\n" + "   </table>\r\n" + "  </td>\r\n"
            + "  </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "</body>");

  }

}
